<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ApiDiff</AssemblyName>
    <RootNamespace>ApiDiff</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
