name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: global.json
    - uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
    - uses: NuGet/setup-nuget@b26b823c478ee115be5c9403e62c90b0bf943843 # v3.1.0
    - uses: darenm/Setup-VSTest@3a16d909a1f3bbc65b52f8270d475d905e7d3e44 # v1.3
    - name: nuget restore
      run: nuget.exe restore krabs\krabs.sln
    - name: build release x64
      run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Release /p:Platform=x64 krabs\krabs.sln
    - name: build debug x64
      run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Debug /p:Platform=x64 krabs\krabs.sln
    - name: build release ARM64
      run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Release /p:Platform=ARM64 krabs\krabs.sln
    - name: build debug ARM64
      run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Debug /p:Platform=ARM64 krabs\krabs.sln
    - name: test native debug
      run: vstest.console.exe krabs\x64\Debug\krabstests.dll
    - name: test debug net462
      run: vstest.console.exe tests\ManagedETWTests\bin\x64\Debug\net462\EtwTestsCS.dll
    - name: test debug net8.0
      run: vstest.console.exe tests\ManagedETWTests\bin\x64\Debug\net8.0\EtwTestsCS.dll
